// <auto-generated />
using System;
using ErpPortfolio.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ErpPortfolio.Api.Data.Migrations
{
    [DbContext(typeof(ErpPortfolioDbContext))]
    [Migration("20260923020209_AdicionaFornecedoresEPedidosCompra")]
    partial class AdicionaFornecedoresEPedidosCompra
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ErpPortfolio.Api.Models.Categoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean")
                        .HasColumnName("ativo");

                    b.Property<DateTime>("DataCadastro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_cadastro")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("nome");

                    b.HasKey("Id")
                        .HasName("pk_categorias");

                    b.HasIndex("Nome")
                        .IsUnique()
                        .HasDatabaseName("ix_categorias_nome");

                    b.ToTable("categorias", (string)null);
                });

            modelBuilder.Entity("ErpPortfolio.Api.Models.Cliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean")
                        .HasColumnName("ativo");

                    b.Property<string>("Cidade")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("cidade");

                    b.Property<DateTime>("DataCadastro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_cadastro")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Documento")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("character varying(14)")
                        .HasColumnName("documento");

                    b.Property<string>("Email")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("email");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("nome");

                    b.Property<string>("Telefone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("telefone");

                    b.Property<string>("Uf")
                        .IsRequired()
                        .HasColumnType("char(2)")
                        .HasColumnName("uf");

                    b.HasKey("Id")
                        .HasName("pk_clientes");

                    b.HasIndex("Documento")
                        .IsUnique()
                        .HasDatabaseName("ix_clientes_documento");

                    b.HasIndex("Nome")
                        .HasDatabaseName("ix_clientes_nome");

                    b.ToTable("clientes", (string)null);
                });

            modelBuilder.Entity("ErpPortfolio.Api.Models.EstoqueMovimentacao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataMovimentacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_movimentacao")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Motivo")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("motivo");

                    b.Property<int?>("PedidoCompraId")
                        .HasColumnType("integer")
                        .HasColumnName("pedido_compra_id");

                    b.Property<int?>("PedidoId")
                        .HasColumnType("integer")
                        .HasColumnName("pedido_id");

                    b.Property<int>("ProdutoId")
                        .HasColumnType("integer")
                        .HasColumnName("produto_id");

                    b.Property<decimal>("Quantidade")
                        .HasColumnType("numeric(12,3)")
                        .HasColumnName("quantidade");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("tipo");

                    b.HasKey("Id")
                        .HasName("pk_estoque_movimentacoes");

                    b.HasIndex("DataMovimentacao")
                        .HasDatabaseName("ix_estoque_movimentacoes_data_movimentacao");

                    b.HasIndex("PedidoCompraId")
                        .HasDatabaseName("ix_estoque_movimentacoes_pedido_compra_id");

                    b.HasIndex("PedidoId")
                        .HasDatabaseName("ix_estoque_movimentacoes_pedido_id");

                    b.HasIndex("ProdutoId")
                        .HasDatabaseName("ix_estoque_movimentacoes_produto_id");

                    b.ToTable("estoque_movimentacoes", null, t =>
                        {
                            t.HasCheckConstraint("ck_estoque_movimentacoes_quantidade", "quantidade > 0");
                        });
                });

            modelBuilder.Entity("ErpPortfolio.Api.Models.Fornecedor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean")
                        .HasColumnName("ativo");

                    b.Property<string>("Cidade")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("cidade");

                    b.Property<DateTime>("DataCadastro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_cadastro")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Documento")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("character varying(14)")
                        .HasColumnName("documento");

                    b.Property<string>("Email")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("email");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("nome");

                    b.Property<string>("Telefone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("telefone");

                    b.Property<string>("Uf")
                        .IsRequired()
                        .HasColumnType("char(2)")
                        .HasColumnName("uf");

                    b.HasKey("Id")
                        .HasName("pk_fornecedores");

                    b.HasIndex("Documento")
                        .IsUnique()
                        .HasDatabaseName("ix_fornecedores_documento");

                    b.HasIndex("Nome")
                        .HasDatabaseName("ix_fornecedores_nome");

                    b.ToTable("fornecedores", (string)null);
                });

            modelBuilder.Entity("ErpPortfolio.Api.Models.ParcelaReceber", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DataRecebimento")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_recebimento");

                    b.Property<int>("NumeroParcela")
                        .HasColumnType("integer")
                        .HasColumnName("numero_parcela");

                    b.Property<int>("PedidoId")
                        .HasColumnType("integer")
                        .HasColumnName("pedido_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<decimal>("Valor")
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("valor");

                    b.Property<DateOnly>("Vencimento")
                        .HasColumnType("date")
                        .HasColumnName("vencimento");

                    b.HasKey("Id")
                        .HasName("pk_parcelas_receber");

                    b.HasIndex("Vencimento")
                        .HasDatabaseName("ix_parcelas_receber_vencimento");

                    b.HasIndex("PedidoId", "NumeroParcela")
                        .IsUnique()
                        .HasDatabaseName("ux_parcelas_receber_pedido_numero");

                    b.ToTable("parcelas_receber", null, t =>
                        {
                            t.HasCheckConstraint("ck_parcelas_receber_numero_parcela", "numero_parcela > 0");

                            t.HasCheckConstraint("ck_parcelas_receber_valor", "valor > 0");
                        });
                });

            modelBuilder.Entity("ErpPortfolio.Api.Models.Pedido", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("Id"));

                    b.Property<int>("ClienteId")
                        .HasColumnType("integer")
                        .HasColumnName("cliente_id");

                    b.Property<DateTime>("DataPedido")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_pedido")
                        .HasDefaultValueSql("now()");

                    b.Property<decimal>("DescontoPercentual")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric(5,2)")
                        .HasDefaultValue(0m)
                        .HasColumnName("desconto_percentual");

                    b.Property<string>("FormaPagamento")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("forma_pagamento");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<decimal>("ValorTotal")
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("valor_total");

                    b.HasKey("Id")
                        .HasName("pk_pedidos");

                    b.HasIndex("ClienteId")
                        .HasDatabaseName("ix_pedidos_cliente_id");

                    b.HasIndex("DataPedido")
                        .HasDatabaseName("ix_pedidos_data_pedido");

                    b.ToTable("pedidos", null, t =>
                        {
                            t.HasCheckConstraint("ck_pedidos_desconto_percentual", "desconto_percentual >= 0 AND desconto_percentual <= 100");

                            t.HasCheckConstraint("ck_pedidos_valor_total", "valor_total >= 0");
                        });
                });

            modelBuilder.Entity("ErpPortfolio.Api.Models.PedidoCompra", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataPedido")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_pedido")
                        .HasDefaultValueSql("now()");

                    b.Property<decimal>("DescontoPercentual")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric(5,2)")
                        .HasDefaultValue(0m)
                        .HasColumnName("desconto_percentual");

                    b.Property<int>("FornecedorId")
                        .HasColumnType("integer")
                        .HasColumnName("fornecedor_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<decimal>("ValorTotal")
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("valor_total");

                    b.HasKey("Id")
                        .HasName("pk_pedidos_compra");

                    b.HasIndex("DataPedido")
                        .HasDatabaseName("ix_pedidos_compra_data_pedido");

                    b.HasIndex("FornecedorId")
                        .HasDatabaseName("ix_pedidos_compra_fornecedor_id");

                    b.ToTable("pedidos_compra", null, t =>
                        {
                            t.HasCheckConstraint("ck_pedidos_compra_desconto_percentual", "desconto_percentual >= 0 AND desconto_percentual <= 100");

                            t.HasCheckConstraint("ck_pedidos_compra_valor_total", "valor_total >= 0");
                        });
                });

            modelBuilder.Entity("ErpPortfolio.Api.Models.PedidoCompraItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("Id"));

                    b.Property<decimal>("DescontoPercentual")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric(5,2)")
                        .HasDefaultValue(0m)
                        .HasColumnName("desconto_percentual");

                    b.Property<int>("PedidoCompraId")
                        .HasColumnType("integer")
                        .HasColumnName("pedido_compra_id");

                    b.Property<decimal>("PrecoUnitario")
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("preco_unitario");

                    b.Property<int>("ProdutoId")
                        .HasColumnType("integer")
                        .HasColumnName("produto_id");

                    b.Property<decimal>("Quantidade")
                        .HasColumnType("numeric(12,3)")
                        .HasColumnName("quantidade");

                    b.HasKey("Id")
                        .HasName("pk_pedido_compra_itens");

                    b.HasIndex("ProdutoId")
                        .HasDatabaseName("ix_pedido_compra_itens_produto_id");

                    b.HasIndex("PedidoCompraId", "ProdutoId")
                        .IsUnique()
                        .HasDatabaseName("ux_pedido_compra_itens_pedido_produto");

                    b.ToTable("pedido_compra_itens", null, t =>
                        {
                            t.HasCheckConstraint("ck_pedido_compra_itens_desconto_percentual", "desconto_percentual >= 0 AND desconto_percentual <= 100");

                            t.HasCheckConstraint("ck_pedido_compra_itens_preco_unitario", "preco_unitario >= 0");

                            t.HasCheckConstraint("ck_pedido_compra_itens_quantidade", "quantidade > 0");
                        });
                });

            modelBuilder.Entity("ErpPortfolio.Api.Models.PedidoItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("Id"));

                    b.Property<decimal>("DescontoPercentual")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric(5,2)")
                        .HasDefaultValue(0m)
                        .HasColumnName("desconto_percentual");

                    b.Property<int>("PedidoId")
                        .HasColumnType("integer")
                        .HasColumnName("pedido_id");

                    b.Property<decimal>("PrecoUnitario")
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("preco_unitario");

                    b.Property<int>("ProdutoId")
                        .HasColumnType("integer")
                        .HasColumnName("produto_id");

                    b.Property<decimal>("Quantidade")
                        .HasColumnType("numeric(12,3)")
                        .HasColumnName("quantidade");

                    b.HasKey("Id")
                        .HasName("pk_pedido_itens");

                    b.HasIndex("ProdutoId")
                        .HasDatabaseName("ix_pedido_itens_produto_id");

                    b.HasIndex("PedidoId", "ProdutoId")
                        .IsUnique()
                        .HasDatabaseName("ux_pedido_itens_pedido_produto");

                    b.ToTable("pedido_itens", null, t =>
                        {
                            t.HasCheckConstraint("ck_pedido_itens_desconto_percentual", "desconto_percentual >= 0 AND desconto_percentual <= 100");

                            t.HasCheckConstraint("ck_pedido_itens_preco_unitario", "preco_unitario >= 0");

                            t.HasCheckConstraint("ck_pedido_itens_quantidade", "quantidade > 0");
                        });
                });

            modelBuilder.Entity("ErpPortfolio.Api.Models.Produto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean")
                        .HasColumnName("ativo");

                    b.Property<int?>("CategoriaId")
                        .HasColumnType("integer")
                        .HasColumnName("categoria_id");

                    b.Property<decimal>("Custo")
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("custo");

                    b.Property<DateTime>("DataCadastro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_cadastro")
                        .HasDefaultValueSql("now()");

                    b.Property<decimal>("EstoqueMinimo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric(12,3)")
                        .HasDefaultValue(0m)
                        .HasColumnName("estoque_minimo");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("nome");

                    b.Property<decimal>("PrecoVenda")
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("preco_venda");

                    b.Property<string>("Sku")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("sku");

                    b.Property<string>("Unidade")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)")
                        .HasColumnName("unidade");

                    b.HasKey("Id")
                        .HasName("pk_produtos");

                    b.HasIndex("CategoriaId")
                        .HasDatabaseName("ix_produtos_categoria_id");

                    b.HasIndex("Nome")
                        .HasDatabaseName("ix_produtos_nome");

                    b.HasIndex("Sku")
                        .IsUnique()
                        .HasDatabaseName("ix_produtos_sku");

                    b.ToTable("produtos", null, t =>
                        {
                            t.HasCheckConstraint("ck_produtos_estoque_minimo", "estoque_minimo >= 0");
                        });
                });

            modelBuilder.Entity("ErpPortfolio.Api.Models.EstoqueMovimentacao", b =>
                {
                    b.HasOne("ErpPortfolio.Api.Models.PedidoCompra", "PedidoCompra")
                        .WithMany()
                        .HasForeignKey("PedidoCompraId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_estoque_movimentacoes_pedidos_compra");

                    b.HasOne("ErpPortfolio.Api.Models.Pedido", "Pedido")
                        .WithMany()
                        .HasForeignKey("PedidoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_estoque_movimentacoes_pedidos");

                    b.HasOne("ErpPortfolio.Api.Models.Produto", "Produto")
                        .WithMany()
                        .HasForeignKey("ProdutoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_estoque_movimentacoes_produtos");

                    b.Navigation("Pedido");

                    b.Navigation("PedidoCompra");

                    b.Navigation("Produto");
                });

            modelBuilder.Entity("ErpPortfolio.Api.Models.ParcelaReceber", b =>
                {
                    b.HasOne("ErpPortfolio.Api.Models.Pedido", "Pedido")
                        .WithMany()
                        .HasForeignKey("PedidoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_parcelas_receber_pedidos");

                    b.Navigation("Pedido");
                });

            modelBuilder.Entity("ErpPortfolio.Api.Models.Pedido", b =>
                {
                    b.HasOne("ErpPortfolio.Api.Models.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_pedidos_clientes");

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("ErpPortfolio.Api.Models.PedidoCompra", b =>
                {
                    b.HasOne("ErpPortfolio.Api.Models.Fornecedor", "Fornecedor")
                        .WithMany()
                        .HasForeignKey("FornecedorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_pedidos_compra_fornecedores");

                    b.Navigation("Fornecedor");
                });

            modelBuilder.Entity("ErpPortfolio.Api.Models.PedidoCompraItem", b =>
                {
                    b.HasOne("ErpPortfolio.Api.Models.PedidoCompra", "PedidoCompra")
                        .WithMany("Itens")
                        .HasForeignKey("PedidoCompraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_pedido_compra_itens_pedidos_compra");

                    b.HasOne("ErpPortfolio.Api.Models.Produto", "Produto")
                        .WithMany()
                        .HasForeignKey("ProdutoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_pedido_compra_itens_produtos");

                    b.Navigation("PedidoCompra");

                    b.Navigation("Produto");
                });

            modelBuilder.Entity("ErpPortfolio.Api.Models.PedidoItem", b =>
                {
                    b.HasOne("ErpPortfolio.Api.Models.Pedido", "Pedido")
                        .WithMany("Itens")
                        .HasForeignKey("PedidoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_pedido_itens_pedidos");

                    b.HasOne("ErpPortfolio.Api.Models.Produto", "Produto")
                        .WithMany()
                        .HasForeignKey("ProdutoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_pedido_itens_produtos");

                    b.Navigation("Pedido");

                    b.Navigation("Produto");
                });

            modelBuilder.Entity("ErpPortfolio.Api.Models.Produto", b =>
                {
                    b.HasOne("ErpPortfolio.Api.Models.Categoria", "Categoria")
                        .WithMany()
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_produtos_categorias");

                    b.Navigation("Categoria");
                });

            modelBuilder.Entity("ErpPortfolio.Api.Models.Pedido", b =>
                {
                    b.Navigation("Itens");
                });

            modelBuilder.Entity("ErpPortfolio.Api.Models.PedidoCompra", b =>
                {
                    b.Navigation("Itens");
                });
#pragma warning restore 612, 618
        }
    }
}
