// <auto-generated />
using System;
using ErpPortfolio.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ErpPortfolio.Api.Data.Migrations
{
    [DbContext(typeof(ErpPortfolioDbContext))]
    [Migration("20260923235828_CriacaoTabelasOrcamentos")]
    partial class CriacaoTabelasOrcamentos
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ErpPortfolio.Api.Models.Categoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean")
                        .HasColumnName("ativo");

                    b.Property<DateTime>("DataCadastro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_cadastro")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("nome");

                    b.HasKey("Id")
                        .HasName("pk_categorias");

                    b.HasIndex("Nome")
                        .IsUnique()
                        .HasDatabaseName("ix_categorias_nome");

                    b.ToTable("categorias", (string)null);
                });

            modelBuilder.Entity("ErpPortfolio.Api.Models.Cliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean")
                        .HasColumnName("ativo");

                    b.Property<string>("Cidade")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("cidade");

                    b.Property<DateTime>("DataCadastro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_cadastro")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Documento")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("character varying(14)")
                        .HasColumnName("documento");

                    b.Property<string>("Email")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("email");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("nome");

                    b.Property<string>("Telefone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("telefone");

                    b.Property<string>("Uf")
                        .IsRequired()
                        .HasColumnType("char(2)")
                        .HasColumnName("uf");

                    b.HasKey("Id")
                        .HasName("pk_clientes");

                    b.HasIndex("Documento")
                        .IsUnique()
                        .HasDatabaseName("ix_clientes_documento");

                    b.HasIndex("Nome")
                        .HasDatabaseName("ix_clientes_nome");

                    b.ToTable("clientes", (string)null);
                });

            modelBuilder.Entity("ErpPortfolio.Api.Models.Comissao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataGeracao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_geracao");

                    b.Property<DateTime?>("DataPagamento")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_pagamento");

                    b.Property<int?>("ParcelaPagarId")
                        .HasColumnType("integer")
                        .HasColumnName("parcela_pagar_id");

                    b.Property<int>("ParcelaReceberId")
                        .HasColumnType("integer")
                        .HasColumnName("parcela_receber_id");

                    b.Property<int>("PedidoId")
                        .HasColumnType("integer")
                        .HasColumnName("pedido_id");

                    b.Property<decimal>("Percentual")
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("percentual");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<decimal>("Valor")
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("valor");

                    b.Property<decimal>("ValorBase")
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("valor_base");

                    b.Property<int>("VendedorId")
                        .HasColumnType("integer")
                        .HasColumnName("vendedor_id");

                    b.HasKey("Id")
                        .HasName("pk_comissoes");

                    b.HasIndex("DataGeracao")
                        .HasDatabaseName("ix_comissoes_data_geracao");

                    b.HasIndex("ParcelaPagarId")
                        .HasDatabaseName("ix_comissoes_parcela_pagar_id");

                    b.HasIndex("ParcelaReceberId")
                        .IsUnique()
                        .HasDatabaseName("ux_comissoes_parcela_receber_id");

                    b.HasIndex("PedidoId")
                        .HasDatabaseName("ix_comissoes_pedido_id");

                    b.HasIndex("VendedorId")
                        .HasDatabaseName("ix_comissoes_vendedor_id");

                    b.ToTable("comissoes", null, t =>
                        {
                            t.HasCheckConstraint("ck_comissoes_percentual", "percentual > 0 AND percentual <= 100");

                            t.HasCheckConstraint("ck_comissoes_valor", "valor > 0");
                        });
                });

            modelBuilder.Entity("ErpPortfolio.Api.Models.EstoqueMovimentacao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataMovimentacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_movimentacao")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Motivo")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("motivo");

                    b.Property<int?>("PedidoCompraId")
                        .HasColumnType("integer")
                        .HasColumnName("pedido_compra_id");

                    b.Property<int?>("PedidoId")
                        .HasColumnType("integer")
                        .HasColumnName("pedido_id");

                    b.Property<int>("ProdutoId")
                        .HasColumnType("integer")
                        .HasColumnName("produto_id");

                    b.Property<decimal>("Quantidade")
                        .HasColumnType("numeric(12,3)")
                        .HasColumnName("quantidade");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("tipo");

                    b.HasKey("Id")
                        .HasName("pk_estoque_movimentacoes");

                    b.HasIndex("DataMovimentacao")
                        .HasDatabaseName("ix_estoque_movimentacoes_data_movimentacao");

                    b.HasIndex("PedidoCompraId")
                        .HasDatabaseName("ix_estoque_movimentacoes_pedido_compra_id");

                    b.HasIndex("PedidoId")
                        .HasDatabaseName("ix_estoque_movimentacoes_pedido_id");

                    b.HasIndex("ProdutoId")
                        .HasDatabaseName("ix_estoque_movimentacoes_produto_id");

                    b.ToTable("estoque_movimentacoes", null, t =>
                        {
                            t.HasCheckConstraint("ck_estoque_movimentacoes_quantidade", "quantidade > 0");
                        });
                });

            modelBuilder.Entity("ErpPortfolio.Api.Models.Fornecedor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean")
                        .HasColumnName("ativo");

                    b.Property<string>("Cidade")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("cidade");

                    b.Property<DateTime>("DataCadastro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_cadastro")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Documento")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("character varying(14)")
                        .HasColumnName("documento");

                    b.Property<string>("Email")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("email");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("nome");

                    b.Property<string>("Telefone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("telefone");

                    b.Property<string>("Uf")
                        .IsRequired()
                        .HasColumnType("char(2)")
                        .HasColumnName("uf");

                    b.HasKey("Id")
                        .HasName("pk_fornecedores");

                    b.HasIndex("Documento")
                        .IsUnique()
                        .HasDatabaseName("ix_fornecedores_documento");

                    b.HasIndex("Nome")
                        .HasDatabaseName("ix_fornecedores_nome");

                    b.ToTable("fornecedores", (string)null);
                });

            modelBuilder.Entity("ErpPortfolio.Api.Models.Orcamento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("Id"));

                    b.Property<int>("ClienteId")
                        .HasColumnType("integer")
                        .HasColumnName("cliente_id");

                    b.Property<DateTime>("DataOrcamento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_orcamento")
                        .HasDefaultValueSql("now()");

                    b.Property<decimal>("DescontoPercentual")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric(5,2)")
                        .HasDefaultValue(0m)
                        .HasColumnName("desconto_percentual");

                    b.Property<string>("FormaPagamento")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("forma_pagamento");

                    b.Property<string>("MotivoPerda")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("motivo_perda");

                    b.Property<string>("Observacoes")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("observacoes");

                    b.Property<int?>("PedidoId")
                        .HasColumnType("integer")
                        .HasColumnName("pedido_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<DateOnly>("Validade")
                        .HasColumnType("date")
                        .HasColumnName("validade");

                    b.Property<decimal>("ValorTotal")
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("valor_total");

                    b.Property<int?>("VendedorId")
                        .HasColumnType("integer")
                        .HasColumnName("vendedor_id");

                    b.HasKey("Id")
                        .HasName("pk_orcamentos");

                    b.HasIndex("ClienteId")
                        .HasDatabaseName("ix_orcamentos_cliente_id");

                    b.HasIndex("DataOrcamento")
                        .HasDatabaseName("ix_orcamentos_data_orcamento");

                    b.HasIndex("PedidoId")
                        .IsUnique()
                        .HasDatabaseName("ux_orcamentos_pedido_id");

                    b.HasIndex("VendedorId")
                        .HasDatabaseName("ix_orcamentos_vendedor_id");

                    b.ToTable("orcamentos", null, t =>
                        {
                            t.HasCheckConstraint("ck_orcamentos_desconto_percentual", "desconto_percentual >= 0 AND desconto_percentual <= 100");

                            t.HasCheckConstraint("ck_orcamentos_status", "(status = 'Aprovado' AND pedido_id IS NOT NULL) OR (status IN ('Aberto', 'Perdido') AND pedido_id IS NULL)");

                            t.HasCheckConstraint("ck_orcamentos_valor_total", "valor_total >= 0");
                        });
                });

            modelBuilder.Entity("ErpPortfolio.Api.Models.OrcamentoItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("Id"));

                    b.Property<decimal>("DescontoPercentual")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric(5,2)")
                        .HasDefaultValue(0m)
                        .HasColumnName("desconto_percentual");

                    b.Property<int>("OrcamentoId")
                        .HasColumnType("integer")
                        .HasColumnName("orcamento_id");

                    b.Property<decimal>("PrecoUnitario")
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("preco_unitario");

                    b.Property<int>("ProdutoId")
                        .HasColumnType("integer")
                        .HasColumnName("produto_id");

                    b.Property<decimal>("Quantidade")
                        .HasColumnType("numeric(12,3)")
                        .HasColumnName("quantidade");

                    b.HasKey("Id")
                        .HasName("pk_orcamento_itens");

                    b.HasIndex("ProdutoId")
                        .HasDatabaseName("ix_orcamento_itens_produto_id");

                    b.HasIndex("OrcamentoId", "ProdutoId")
                        .IsUnique()
                        .HasDatabaseName("ux_orcamento_itens_orcamento_produto");

                    b.ToTable("orcamento_itens", null, t =>
                        {
                            t.HasCheckConstraint("ck_orcamento_itens_desconto_percentual", "desconto_percentual >= 0 AND desconto_percentual <= 100");

                            t.HasCheckConstraint("ck_orcamento_itens_preco_unitario", "preco_unitario >= 0");

                            t.HasCheckConstraint("ck_orcamento_itens_quantidade", "quantidade > 0");
                        });
                });

            modelBuilder.Entity("ErpPortfolio.Api.Models.ParcelaPagar", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DataPagamento")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_pagamento");

                    b.Property<string>("Descricao")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("descricao");

                    b.Property<string>("Favorecido")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("favorecido");

                    b.Property<int>("NumeroParcela")
                        .HasColumnType("integer")
                        .HasColumnName("numero_parcela");

                    b.Property<string>("Origem")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("Compra")
                        .HasColumnName("origem");

                    b.Property<int?>("PedidoCompraId")
                        .HasColumnType("integer")
                        .HasColumnName("pedido_compra_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<int>("TotalParcelas")
                        .HasColumnType("integer")
                        .HasColumnName("total_parcelas");

                    b.Property<decimal>("Valor")
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("valor");

                    b.Property<DateOnly>("Vencimento")
                        .HasColumnType("date")
                        .HasColumnName("vencimento");

                    b.Property<int?>("VendedorId")
                        .HasColumnType("integer")
                        .HasColumnName("vendedor_id");

                    b.HasKey("Id")
                        .HasName("pk_parcelas_pagar");

                    b.HasIndex("Vencimento")
                        .HasDatabaseName("ix_parcelas_pagar_vencimento");

                    b.HasIndex("VendedorId")
                        .HasDatabaseName("ix_parcelas_pagar_vendedor_id");

                    b.HasIndex("PedidoCompraId", "NumeroParcela")
                        .IsUnique()
                        .HasDatabaseName("ux_parcelas_pagar_pedido_compra_numero");

                    b.ToTable("parcelas_pagar", null, t =>
                        {
                            t.HasCheckConstraint("ck_parcelas_pagar_numero_parcela", "numero_parcela > 0");

                            t.HasCheckConstraint("ck_parcelas_pagar_origem", "(origem = 'Compra' AND pedido_compra_id IS NOT NULL) OR (origem = 'Comissao' AND vendedor_id IS NOT NULL) OR (origem = 'Avulsa' AND descricao IS NOT NULL)");

                            t.HasCheckConstraint("ck_parcelas_pagar_total_parcelas", "total_parcelas >= numero_parcela");

                            t.HasCheckConstraint("ck_parcelas_pagar_valor", "valor > 0");
                        });
                });

            modelBuilder.Entity("ErpPortfolio.Api.Models.ParcelaReceber", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DataRecebimento")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_recebimento");

                    b.Property<int>("NumeroParcela")
                        .HasColumnType("integer")
                        .HasColumnName("numero_parcela");

                    b.Property<int>("PedidoId")
                        .HasColumnType("integer")
                        .HasColumnName("pedido_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<decimal>("Valor")
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("valor");

                    b.Property<DateOnly>("Vencimento")
                        .HasColumnType("date")
                        .HasColumnName("vencimento");

                    b.HasKey("Id")
                        .HasName("pk_parcelas_receber");

                    b.HasIndex("Vencimento")
                        .HasDatabaseName("ix_parcelas_receber_vencimento");

                    b.HasIndex("PedidoId", "NumeroParcela")
                        .IsUnique()
                        .HasDatabaseName("ux_parcelas_receber_pedido_numero");

                    b.ToTable("parcelas_receber", null, t =>
                        {
                            t.HasCheckConstraint("ck_parcelas_receber_numero_parcela", "numero_parcela > 0");

                            t.HasCheckConstraint("ck_parcelas_receber_valor", "valor > 0");
                        });
                });

            modelBuilder.Entity("ErpPortfolio.Api.Models.Pedido", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("Id"));

                    b.Property<int>("ClienteId")
                        .HasColumnType("integer")
                        .HasColumnName("cliente_id");

                    b.Property<DateTime>("DataPedido")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_pedido")
                        .HasDefaultValueSql("now()");

                    b.Property<decimal>("DescontoPercentual")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric(5,2)")
                        .HasDefaultValue(0m)
                        .HasColumnName("desconto_percentual");

                    b.Property<string>("FormaPagamento")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("forma_pagamento");

                    b.Property<decimal?>("PercentualComissao")
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("percentual_comissao");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<decimal>("ValorTotal")
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("valor_total");

                    b.Property<int?>("VendedorId")
                        .HasColumnType("integer")
                        .HasColumnName("vendedor_id");

                    b.HasKey("Id")
                        .HasName("pk_pedidos");

                    b.HasIndex("ClienteId")
                        .HasDatabaseName("ix_pedidos_cliente_id");

                    b.HasIndex("DataPedido")
                        .HasDatabaseName("ix_pedidos_data_pedido");

                    b.HasIndex("VendedorId")
                        .HasDatabaseName("ix_pedidos_vendedor_id");

                    b.ToTable("pedidos", null, t =>
                        {
                            t.HasCheckConstraint("ck_pedidos_desconto_percentual", "desconto_percentual >= 0 AND desconto_percentual <= 100");

                            t.HasCheckConstraint("ck_pedidos_percentual_comissao", "percentual_comissao >= 0 AND percentual_comissao <= 100");

                            t.HasCheckConstraint("ck_pedidos_valor_total", "valor_total >= 0");
                        });
                });

            modelBuilder.Entity("ErpPortfolio.Api.Models.PedidoCompra", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataPedido")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_pedido")
                        .HasDefaultValueSql("now()");

                    b.Property<decimal>("DescontoPercentual")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric(5,2)")
                        .HasDefaultValue(0m)
                        .HasColumnName("desconto_percentual");

                    b.Property<int>("FornecedorId")
                        .HasColumnType("integer")
                        .HasColumnName("fornecedor_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<decimal>("ValorTotal")
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("valor_total");

                    b.HasKey("Id")
                        .HasName("pk_pedidos_compra");

                    b.HasIndex("DataPedido")
                        .HasDatabaseName("ix_pedidos_compra_data_pedido");

                    b.HasIndex("FornecedorId")
                        .HasDatabaseName("ix_pedidos_compra_fornecedor_id");

                    b.ToTable("pedidos_compra", null, t =>
                        {
                            t.HasCheckConstraint("ck_pedidos_compra_desconto_percentual", "desconto_percentual >= 0 AND desconto_percentual <= 100");

                            t.HasCheckConstraint("ck_pedidos_compra_valor_total", "valor_total >= 0");
                        });
                });

            modelBuilder.Entity("ErpPortfolio.Api.Models.PedidoCompraItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("Id"));

                    b.Property<decimal>("DescontoPercentual")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric(5,2)")
                        .HasDefaultValue(0m)
                        .HasColumnName("desconto_percentual");

                    b.Property<int>("PedidoCompraId")
                        .HasColumnType("integer")
                        .HasColumnName("pedido_compra_id");

                    b.Property<decimal>("PrecoUnitario")
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("preco_unitario");

                    b.Property<int>("ProdutoId")
                        .HasColumnType("integer")
                        .HasColumnName("produto_id");

                    b.Property<decimal>("Quantidade")
                        .HasColumnType("numeric(12,3)")
                        .HasColumnName("quantidade");

                    b.HasKey("Id")
                        .HasName("pk_pedido_compra_itens");

                    b.HasIndex("ProdutoId")
                        .HasDatabaseName("ix_pedido_compra_itens_produto_id");

                    b.HasIndex("PedidoCompraId", "ProdutoId")
                        .IsUnique()
                        .HasDatabaseName("ux_pedido_compra_itens_pedido_produto");

                    b.ToTable("pedido_compra_itens", null, t =>
                        {
                            t.HasCheckConstraint("ck_pedido_compra_itens_desconto_percentual", "desconto_percentual >= 0 AND desconto_percentual <= 100");

                            t.HasCheckConstraint("ck_pedido_compra_itens_preco_unitario", "preco_unitario >= 0");

                            t.HasCheckConstraint("ck_pedido_compra_itens_quantidade", "quantidade > 0");
                        });
                });

            modelBuilder.Entity("ErpPortfolio.Api.Models.PedidoItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("Id"));

                    b.Property<decimal>("DescontoPercentual")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric(5,2)")
                        .HasDefaultValue(0m)
                        .HasColumnName("desconto_percentual");

                    b.Property<int>("PedidoId")
                        .HasColumnType("integer")
                        .HasColumnName("pedido_id");

                    b.Property<decimal>("PrecoUnitario")
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("preco_unitario");

                    b.Property<int>("ProdutoId")
                        .HasColumnType("integer")
                        .HasColumnName("produto_id");

                    b.Property<decimal>("Quantidade")
                        .HasColumnType("numeric(12,3)")
                        .HasColumnName("quantidade");

                    b.HasKey("Id")
                        .HasName("pk_pedido_itens");

                    b.HasIndex("ProdutoId")
                        .HasDatabaseName("ix_pedido_itens_produto_id");

                    b.HasIndex("PedidoId", "ProdutoId")
                        .IsUnique()
                        .HasDatabaseName("ux_pedido_itens_pedido_produto");

                    b.ToTable("pedido_itens", null, t =>
                        {
                            t.HasCheckConstraint("ck_pedido_itens_desconto_percentual", "desconto_percentual >= 0 AND desconto_percentual <= 100");

                            t.HasCheckConstraint("ck_pedido_itens_preco_unitario", "preco_unitario >= 0");

                            t.HasCheckConstraint("ck_pedido_itens_quantidade", "quantidade > 0");
                        });
                });

            modelBuilder.Entity("ErpPortfolio.Api.Models.Produto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean")
                        .HasColumnName("ativo");

                    b.Property<int?>("CategoriaId")
                        .HasColumnType("integer")
                        .HasColumnName("categoria_id");

                    b.Property<decimal>("Custo")
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("custo");

                    b.Property<DateTime>("DataCadastro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_cadastro")
                        .HasDefaultValueSql("now()");

                    b.Property<decimal>("EstoqueMinimo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric(12,3)")
                        .HasDefaultValue(0m)
                        .HasColumnName("estoque_minimo");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("nome");

                    b.Property<decimal>("PrecoVenda")
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("preco_venda");

                    b.Property<string>("Sku")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("sku");

                    b.Property<string>("Unidade")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)")
                        .HasColumnName("unidade");

                    b.HasKey("Id")
                        .HasName("pk_produtos");

                    b.HasIndex("CategoriaId")
                        .HasDatabaseName("ix_produtos_categoria_id");

                    b.HasIndex("Nome")
                        .HasDatabaseName("ix_produtos_nome");

                    b.HasIndex("Sku")
                        .IsUnique()
                        .HasDatabaseName("ix_produtos_sku");

                    b.ToTable("produtos", null, t =>
                        {
                            t.HasCheckConstraint("ck_produtos_estoque_minimo", "estoque_minimo >= 0");
                        });
                });

            modelBuilder.Entity("ErpPortfolio.Api.Models.Vendedor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean")
                        .HasColumnName("ativo");

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasColumnType("char(11)")
                        .HasColumnName("cpf");

                    b.Property<DateTime>("DataCadastro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_cadastro")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Email")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("email");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("nome");

                    b.Property<decimal>("PercentualComissao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric(5,2)")
                        .HasDefaultValue(0m)
                        .HasColumnName("percentual_comissao");

                    b.Property<string>("Telefone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("telefone");

                    b.HasKey("Id")
                        .HasName("pk_vendedores");

                    b.HasIndex("Cpf")
                        .IsUnique()
                        .HasDatabaseName("ix_vendedores_cpf");

                    b.HasIndex("Nome")
                        .HasDatabaseName("ix_vendedores_nome");

                    b.ToTable("vendedores", null, t =>
                        {
                            t.HasCheckConstraint("ck_vendedores_percentual_comissao", "percentual_comissao >= 0 AND percentual_comissao <= 100");
                        });
                });

            modelBuilder.Entity("ErpPortfolio.Api.Models.Comissao", b =>
                {
                    b.HasOne("ErpPortfolio.Api.Models.ParcelaPagar", "ParcelaPagar")
                        .WithMany()
                        .HasForeignKey("ParcelaPagarId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_comissoes_parcelas_pagar");

                    b.HasOne("ErpPortfolio.Api.Models.ParcelaReceber", "ParcelaReceber")
                        .WithMany()
                        .HasForeignKey("ParcelaReceberId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_comissoes_parcelas_receber");

                    b.HasOne("ErpPortfolio.Api.Models.Pedido", "Pedido")
                        .WithMany()
                        .HasForeignKey("PedidoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_comissoes_pedidos");

                    b.HasOne("ErpPortfolio.Api.Models.Vendedor", "Vendedor")
                        .WithMany()
                        .HasForeignKey("VendedorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_comissoes_vendedores");

                    b.Navigation("ParcelaPagar");

                    b.Navigation("ParcelaReceber");

                    b.Navigation("Pedido");

                    b.Navigation("Vendedor");
                });

            modelBuilder.Entity("ErpPortfolio.Api.Models.EstoqueMovimentacao", b =>
                {
                    b.HasOne("ErpPortfolio.Api.Models.PedidoCompra", "PedidoCompra")
                        .WithMany()
                        .HasForeignKey("PedidoCompraId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_estoque_movimentacoes_pedidos_compra");

                    b.HasOne("ErpPortfolio.Api.Models.Pedido", "Pedido")
                        .WithMany()
                        .HasForeignKey("PedidoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_estoque_movimentacoes_pedidos");

                    b.HasOne("ErpPortfolio.Api.Models.Produto", "Produto")
                        .WithMany()
                        .HasForeignKey("ProdutoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_estoque_movimentacoes_produtos");

                    b.Navigation("Pedido");

                    b.Navigation("PedidoCompra");

                    b.Navigation("Produto");
                });

            modelBuilder.Entity("ErpPortfolio.Api.Models.Orcamento", b =>
                {
                    b.HasOne("ErpPortfolio.Api.Models.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_orcamentos_clientes");

                    b.HasOne("ErpPortfolio.Api.Models.Pedido", "Pedido")
                        .WithMany()
                        .HasForeignKey("PedidoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_orcamentos_pedidos");

                    b.HasOne("ErpPortfolio.Api.Models.Vendedor", "Vendedor")
                        .WithMany()
                        .HasForeignKey("VendedorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_orcamentos_vendedores");

                    b.Navigation("Cliente");

                    b.Navigation("Pedido");

                    b.Navigation("Vendedor");
                });

            modelBuilder.Entity("ErpPortfolio.Api.Models.OrcamentoItem", b =>
                {
                    b.HasOne("ErpPortfolio.Api.Models.Orcamento", "Orcamento")
                        .WithMany("Itens")
                        .HasForeignKey("OrcamentoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_orcamento_itens_orcamentos");

                    b.HasOne("ErpPortfolio.Api.Models.Produto", "Produto")
                        .WithMany()
                        .HasForeignKey("ProdutoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_orcamento_itens_produtos");

                    b.Navigation("Orcamento");

                    b.Navigation("Produto");
                });

            modelBuilder.Entity("ErpPortfolio.Api.Models.ParcelaPagar", b =>
                {
                    b.HasOne("ErpPortfolio.Api.Models.PedidoCompra", "PedidoCompra")
                        .WithMany()
                        .HasForeignKey("PedidoCompraId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_parcelas_pagar_pedidos_compra");

                    b.HasOne("ErpPortfolio.Api.Models.Vendedor", "Vendedor")
                        .WithMany()
                        .HasForeignKey("VendedorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_parcelas_pagar_vendedores");

                    b.Navigation("PedidoCompra");

                    b.Navigation("Vendedor");
                });

            modelBuilder.Entity("ErpPortfolio.Api.Models.ParcelaReceber", b =>
                {
                    b.HasOne("ErpPortfolio.Api.Models.Pedido", "Pedido")
                        .WithMany()
                        .HasForeignKey("PedidoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_parcelas_receber_pedidos");

                    b.Navigation("Pedido");
                });

            modelBuilder.Entity("ErpPortfolio.Api.Models.Pedido", b =>
                {
                    b.HasOne("ErpPortfolio.Api.Models.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_pedidos_clientes");

                    b.HasOne("ErpPortfolio.Api.Models.Vendedor", "Vendedor")
                        .WithMany()
                        .HasForeignKey("VendedorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_pedidos_vendedores");

                    b.Navigation("Cliente");

                    b.Navigation("Vendedor");
                });

            modelBuilder.Entity("ErpPortfolio.Api.Models.PedidoCompra", b =>
                {
                    b.HasOne("ErpPortfolio.Api.Models.Fornecedor", "Fornecedor")
                        .WithMany()
                        .HasForeignKey("FornecedorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_pedidos_compra_fornecedores");

                    b.Navigation("Fornecedor");
                });

            modelBuilder.Entity("ErpPortfolio.Api.Models.PedidoCompraItem", b =>
                {
                    b.HasOne("ErpPortfolio.Api.Models.PedidoCompra", "PedidoCompra")
                        .WithMany("Itens")
                        .HasForeignKey("PedidoCompraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_pedido_compra_itens_pedidos_compra");

                    b.HasOne("ErpPortfolio.Api.Models.Produto", "Produto")
                        .WithMany()
                        .HasForeignKey("ProdutoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_pedido_compra_itens_produtos");

                    b.Navigation("PedidoCompra");

                    b.Navigation("Produto");
                });

            modelBuilder.Entity("ErpPortfolio.Api.Models.PedidoItem", b =>
                {
                    b.HasOne("ErpPortfolio.Api.Models.Pedido", "Pedido")
                        .WithMany("Itens")
                        .HasForeignKey("PedidoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_pedido_itens_pedidos");

                    b.HasOne("ErpPortfolio.Api.Models.Produto", "Produto")
                        .WithMany()
                        .HasForeignKey("ProdutoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_pedido_itens_produtos");

                    b.Navigation("Pedido");

                    b.Navigation("Produto");
                });

            modelBuilder.Entity("ErpPortfolio.Api.Models.Produto", b =>
                {
                    b.HasOne("ErpPortfolio.Api.Models.Categoria", "Categoria")
                        .WithMany()
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_produtos_categorias");

                    b.Navigation("Categoria");
                });

            modelBuilder.Entity("ErpPortfolio.Api.Models.Orcamento", b =>
                {
                    b.Navigation("Itens");
                });

            modelBuilder.Entity("ErpPortfolio.Api.Models.Pedido", b =>
                {
                    b.Navigation("Itens");
                });

            modelBuilder.Entity("ErpPortfolio.Api.Models.PedidoCompra", b =>
                {
                    b.Navigation("Itens");
                });
#pragma warning restore 612, 618
        }
    }
}
